[package]
name = "quranize-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
quranize = "0.7"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
serde = { version = "1.0", features = ["derive"] }
