[package]
name = "quranize-wasm"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
quranize = "0.11"
wasm-bindgen = "0.2"
serde = "1.0"
serde-wasm-bindgen = "0.6"

[dev-dependencies]
pretty_assertions = "1"
