name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend 🛎️
        uses: actions/checkout@v3

      - name: Checkout Engine 🛎️
        uses: actions/checkout@v3
        with:
          repository: github.com/alpancs/quranize-rs
          path: ../quranize-rs

      - name: Install Tools 🔧
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build 🔨
        run: |
          cd ../quranize-rs
          wasm-pack build --release --target=web --no-typescript
          cp -v pkg/quranize.js pkg/quranize_bg.wasm  $GITHUB_WORKSPACE/script
          cd -

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "."
