name: Deploy static content to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
      - run: wasm-pack build --release --target=web --no-typescript --out-dir=web-app/scripts/quranize --out-name=quranize
      - run: wget https://unpkg.com/vue@3/dist/vue.esm-browser.prod.js -O web-app/scripts/vue.esm-browser.js
      - uses: actions/upload-artifact@v3
        with:
          name: build-scripts
          path: |
            web-app/scripts/quranize.js
            web-app/scripts/quranize_bg.wasm
            web-app/scripts/vue.esm-browser.js
  build-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css -O web-app/styles/bulma.min.css
      - run: wget https://use.fontawesome.com/releases/v6.4.0/fontawesome-free-6.4.0-web.zip
      - run: unzip fontawesome-free-6.4.0-web.zip "fontawesome-free-6.4.0-web/webfonts/**" "fontawesome-free-6.4.0-web/css/**"
      - run: mv fontawesome-free-6.4.0-web web-app/styles/fontawesome
      - uses: actions/upload-artifact@v3
        with:
          name: build-styles
          path: |
            web-app/styles/app.css
            web-app/styles/bulma.min.css
            web-app/styles/fontawesome
  deploy:
    needs:
      - build-scripts
      - build-styles
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
          path: web-app/scripts
      - uses: actions/download-artifact@v3
        with:
          name: build-styles
          path: web-app/styles
      - uses: actions/upload-pages-artifact@v1
        with:
          path: web-app
      - uses: actions/deploy-pages@v1
        id: deployment
