name: Deploy static content to Pages

on:
  push:
    branches: [main, quranize-0.7-usage]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash
      - run: wasm-pack build --release --target=web --no-typescript --out-dir=web-app/scripts --out-name=quranize
      - run: wget https://unpkg.com/vue@3.2.40/dist/vue.global.prod.js -O web-app/scripts/vue.js
      - uses: actions/upload-artifact@v3
        with:
          name: build-scripts
          path: |
            web-app/scripts/quranize.js
            web-app/scripts/quranize_bg.wasm
            web-app/scripts/vue.js
  build-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: jgthms/bulma
          ref: "0.9.4"
          path: web-app/styles/bulma
      - run: curl -L https://github.com/sass/dart-sass/releases/download/1.54.8/dart-sass-1.54.8-linux-x64.tar.gz | tar xzv
      - run: dart-sass/sass --no-source-map --style=compressed web-app/styles/app.scss web-app/styles/app.css
      - run: wget https://use.fontawesome.com/releases/v6.2.0/fontawesome-free-6.2.0-web.zip
      - run: unzip fontawesome-free-6.2.0-web.zip "fontawesome-free-6.2.0-web/webfonts/**" "fontawesome-free-6.2.0-web/css/**"
      - run: mv fontawesome-free-6.2.0-web web-app/styles/fontawesome
      - uses: actions/upload-artifact@v3
        with:
          name: build-styles
          path: |
            web-app/styles/app.css
            web-app/styles/fontawesome
  deploy:
    needs:
      - build-scripts
      - build-styles
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: actions/download-artifact@v3
        with:
          name: build-scripts
          path: web-app/scripts
      - uses: actions/download-artifact@v3
        with:
          name: build-styles
          path: web-app/styles
      - uses: actions/upload-pages-artifact@v1
        with:
          path: web-app
      - uses: actions/deploy-pages@v1
        id: deployment
